workers_dev = true
name = "word-combo"
compatibility_date = "2024-11-18"
main = "./build/server/assets/server-build2.js"
assets = { directory = "./build/client/" }

kv_namespaces = [
  { binding = "WORDS_OF_THE_DAY", id = "f4050b21d72b4dd9be3c43f9ba70fd4c" }
]